apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubed
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs: ["get", "create"]
- apiGroups:
  - kubed.appscode.com
  resources:
  - restics
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs: ["list", "watch", "update"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["list", "watch", "update"]
- apiGroups: [""]
  resources:
  - namespaces
  - replicationcontrollers
  verbs: ["list", "watch", "update"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubed
subjects:
- kind: ServiceAccount
  name: kubed
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubed
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kubed
  name: kubed
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubed
  template:
    metadata:
      labels:
        app: kubed
    spec:
      serviceAccountName: kubed
      containers:
      - name: kubed
        args:
        - run
        - --v=3
        image: appscode/kubed:0.1.0
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /tmp
            name: scratchdir
      volumes:
        - emptyDir: {}
          name: scratchdir
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubed
  name: kubed
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: kubed
