apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubed
rules:
- apiGroups:
  - voyager.appscode.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - monitoring.appscode.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - stash.appscode.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - kubedb.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - monitoring.coreos.com
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - extensions
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups:
  - apps
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["get", "create", "update"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["abac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["*"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubed
subjects:
- kind: ServiceAccount
  name: kubed
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubed
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubed
  namespace: kube-system
  labels:
    app: kubed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubed
  template:
    metadata:
      labels:
        app: kubed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: kubed
      containers:
      - name: kubed
        args:
        - run
        - --v=3
        image: appscode/kubed:canary
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /srv/kubed
          - name: scratchdir
            mountPath: /tmp
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      volumes:
        - name: config
          configMap:
            name: kubed
        - name: scratchdir
          emptyDir: {}          
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubed
  name: kubed
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: kubed
