apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubed-operator
  namespace: ${KUBED_NAMESPACE}
  labels:
    app: kubed
  initializers:
    pending: []
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubed
  template:
    metadata:
      labels:
        app: kubed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: ${KUBED_SERVICE_ACCOUNT}
      imagePullSecrets: [${KUBED_IMAGE_PULL_SECRET}]
      containers:
      - name: operator
        image: ${KUBED_DOCKER_REGISTRY}/kubed:${KUBED_IMAGE_TAG}
        imagePullPolicy: ${KUBED_IMAGE_PULL_POLICY}
        args:
        - run
        - --v=3
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --ops-address=:56790
        - --enable-analytics=${KUBED_ENABLE_ANALYTICS}
        ports:
        - containerPort: 8443
        - containerPort: 56790
        volumeMounts:
        - name: config
          mountPath: /srv/kubed
        - name: scratch
          mountPath: /tmp
        - mountPath: /var/serving-cert
          name: serving-cert
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
      volumes:
      - name: config
        secret:
          secretName: kubed-config
      - name: scratch
        emptyDir: {}
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: kubed-apiserver-cert
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
---
# kube lacks the service serving cert signer, so provide a manual secret for it
apiVersion: v1
kind: Secret
metadata:
  name: kubed-apiserver-cert
  namespace: ${KUBED_NAMESPACE}
  labels:
    app: kubed
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_SERVING_CERT}
  tls.key: ${TLS_SERVING_KEY}
---
# to be able to expose TSB inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: kubed-operator
  namespace: ${KUBED_NAMESPACE}
  labels:
    app: kubed
spec:
  ports:
  - name: api
    port: 443
    targetPort: 8443
  - name: ops
    port: 56790
    targetPort: 56790
  selector:
    app: kubed
