{{- if not .Values.config.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "config-syncer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-syncer.labels" . | nindent 4 }}
data:
  {{- if .Values.config.kubeconfigContent }}
  kubeconfig: {{ .Values.config.kubeconfigContent | trim | b64enc | quote }}
  {{- end }}
{{- end }}
