eventForwarder:
  nodeAdded:
    handle: true
  storageAdded:
    handle: true
  ingressAdded:
    handle: true
  warningEvents:
    handle: true
    namespaces:
    - kube-system
  receiver:
    notifier: mailgun
    to:
    - ops@example.com
notifierSecretName: notifier-config
