# Default values for kubed.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Overrides name template
nameOverride: ""
# Overrides fullname template
fullnameOverride: ""

# Number of Config Syncer operator replicas to create (only 1 is supported)
replicaCount: 1

operator:
  # Docker registry used to pull Config Syncer operator image
  registry: appscode
  # Config Syncer operator container image
  repository: kubed
  # Config Syncer operator container image tag
  tag: v0.13.2
  # Compute Resources required by the operator container
  resources: {}
  # Security options the operator container should run with
  securityContext: {}

# Specify an array of imagePullSecrets.
# Secrets must be manually created in the namespace.
#
# Example:
# helm template charts/kubed \
#   --set imagePullSecrets[0].name=sec0 \
#   --set imagePullSecrets[1].name=sec1
imagePullSecrets: []

# Container image pull policy
imagePullPolicy: IfNotPresent

# If true, installs Config Syncer operator as critical addon
criticalAddon: false

# Log level for operator
logLevel: 3

# Annotations applied to operator deployment
annotations: {}

# Annotations passed to operator pod(s).
podAnnotations: {}

# Node labels for pod assignment
nodeSelector: {}

# Tolerations for pod assignment
tolerations: []

# Affinity rules for pod assignment
affinity: {}

# Security options the operator pod should run with.
podSecurityContext:  # +doc-gen:break
  # ensure that s/a token is readable xref: https://issues.k8s.io/70679
  fsGroup: 65535

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

apiserver:
  # Port used by Config Syncer server
  securePort: "8443"
  # If true, uses kube-apiserver FQDN for AKS cluster to workaround https://github.com/Azure/AKS/issues/522 (default true)
  useKubeapiserverFqdnForAks: true
  healthcheck:
    # healthcheck configures the readiness and liveliness probes for the operator pod.
    enabled: false
  servingCerts:
    # If true, generates on install/upgrade the certs that allow the kube-apiserver (and potentially ServiceMonitor)
    # to authenticate operators pods. Otherwise specify certs in `apiserver.servingCerts.{caCrt, serverCrt, serverKey}`.
    generate: true
    # CA certficate used by serving certificate of Config Syncer server.
    caCrt: ""
    # Serving certficate used by Config Syncer server.
    serverCrt: ""
    # Private key for the serving certificate used by Config Syncer server.
    serverKey: ""

# If true, sends usage analytics
enableAnalytics: true

config:
  # Set cluster-name to something meaningful to you, say, prod, prod-us-east, qa, etc.
  # so that you can distinguish notifications sent by kubed
  clusterName: unicorn
  # If set, configmaps and secrets from only this namespace will be synced
  configSourceNamespace: ""
  # kubeconfig file content for configmap and secret syncer
  kubeconfigContent: ""
#  additionalOptions:
#    - --authentication-skip-lookup
