apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "name" . }}"
        release: "{{ .Release.Name }}"
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
{{- if .Values.rbac.install }}
      serviceAccountName: {{ template "fullname" . }}
{{- end }}
      containers:
      - name: kubed
        args:
        - run
        - --v=3
        image: '{{ .Values.kubed.image }}:{{ .Values.kubed.tag }}'
        imagePullPolicy: '{{ .Values.kubed.pullPolicy }}'
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /srv/kubed
          - name: scratchdir
            mountPath: /tmp
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      volumes:
        - name: config
          configMap:
            name: kubed
        - name: scratchdir
          emptyDir: {}
