apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ template "name" . }}"
        release: "{{ .Release.Name }}"
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
      - name: kubed
        args:
        - run
        - --v=3
        - --api.address=:8080
        - --web.address=:56790
        image: '{{ .Values.kubed.image }}:{{ .Values.kubed.tag }}'
        imagePullPolicy: '{{ .Values.kubed.pullPolicy }}'
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
        - containerPort: 56790
          name: web
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /srv/kubed
          - name: scratch
            mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: kubed
        - name: scratch
          emptyDir: {}
