{{ define "kubed.config" }}
clusterName: "{{ .Values.config.clusterName }}"
enableConfigSyncer: {{ .Values.config.enableConfigSyncer }}
{{- if .Values.config.enableEventForwarder }}
eventForwarder:
  rules:
  - namespaces:
    - kube-system
    operations:
    - CREATE
    resources:
    - group: ""
      resources:
      - events
  - operations:
    - CREATE
    resources:
    - group: ""
      resources:
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
    - group: storage.k8s.io
      resources:
      - storageclasses
    - group: extensions
      resources:
      - ingresses
    - group: voyager.appscode.com
      resources:
      - ingresses
    - group: certificates.k8s.io
      resources:
      - certificatesigningrequests
    - group: networking.k8s.io
      resources:
      - networkpolicies
{{- end }}
{{- if .Values.config.enableRecycleBin }}
recycleBin:
  handleUpdates: false
  path: /tmp/kubed/trash
  ttl: 168h0m0s
{{- end }}
{{- if .Values.config.include }}
{{ .Values.config.include | toYaml }}
{{- end }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kubed.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "kubed.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: {{ (include "kubed.config" .) | trim | b64enc | quote }}
